import os

RABBITMQ_HOST = os.environ.get("RABBITMQ_HOST")
RABBITMQ_EMAIL_QUEUE = os.environ.get("RABBITMQ_EMAIL_QUEUE")
RABBITMQ_EMAIL_ROUTING_KEY = os.environ.get("RABBITMQ_EMAIL_ROUTING_KEY")
RABBITMQ_USER = os.environ.get("RABBITMQ_DEFAULT_USER")
RABBITMQ_PASSWORD = os.environ.get("RABBITMQ_DEFAULT_PASSWORD")
